import Head from 'next/head';
import BlogPostList from '../../../components/BlogPostList';
import { getAllTags, getAllPublished } from '../../../utilities/directus';

import React from 'react';

export const Tag = ({ postsByTag }) => {
  return (
    <>
      <Head>
        <title>SRBlog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BlogPostList blog_posts={postsByTag} />
    </>
  );
};

export const getStaticProps = async ({ params }) => {
  const data = await getAllPublished();
  const postsByTag = data.data.blog_posts.filter((post) => {
    return post.tags.some(
      (tag) => tag.tags_id.tag_name.toLowerCase() === params.tag
    );
  });

  return {
    props: {
      postsByTag,
    },
    revalidate: 1,
  };
};

export const getStaticPaths = async () => {
  const data = await getAllTags();

  const paths = data.map((tag_name) => ({
    params: { tag: tag_name.toLowerCase() },
  }));

  return {
    paths,
    fallback: 'blocking',
  };
};

export default Tag;
